Add-Type -AssemblyName System.Windows.Forms

# Create the form
$form = New-Object System.Windows.Forms.Form
$form.Text = "Application Launcher"
$form.Size = New-Object System.Drawing.Size(400, 300)
$form.StartPosition = "CenterScreen"

# Create a hashtable to store priority selections for each selected exe
$prioritySelections = @{}

# Create the list box to select applications
$listBox = New-Object System.Windows.Forms.ListBox
$listBox.Location = New-Object System.Drawing.Point(20, 20)
$listBox.Size = New-Object System.Drawing.Size(200, 150)
$form.Controls.Add($listBox)

# Create the list box to select priority
$priorityListBox = New-Object System.Windows.Forms.ListBox
$priorityListBox.Location = New-Object System.Drawing.Point(230, 20)
$priorityListBox.Size = New-Object System.Drawing.Size(150, 150)
$priorityListBox.Items.AddRange(@("Low", "Normal", "High"))
$form.Controls.Add($priorityListBox)

# Create the button to add executable files
$addButton = New-Object System.Windows.Forms.Button
$addButton.Location = New-Object System.Drawing.Point(20, 200)
$addButton.Size = New-Object System.Drawing.Size(120, 30)
$addButton.Text = "Add Executables"
$addButton.Add_Click({
    # Open the open file dialog
    $openFileDialog = New-Object System.Windows.Forms.OpenFileDialog
    $openFileDialog.Filter = "Executable Files (*.exe)|*.exe"
    $openFileDialog.Multiselect = $true
    if ($openFileDialog.ShowDialog() -eq "OK") {
        # Add the selected executable files to the list box
        foreach ($file in $openFileDialog.FileNames) {
            $listBox.Items.Add($file)
            $prioritySelections[$file] = "Normal" # Default priority is Normal
        }
    }
})
$form.Controls.Add($addButton)

# Create the button to generate the batch script
$generateButton = New-Object System.Windows.Forms.Button
$generateButton.Location = New-Object System.Drawing.Point(20, 240)
$generateButton.Size = New-Object System.Drawing.Size(120, 30)
$generateButton.Text = "Generate Batch"
$generateButton.Add_Click({
    # Get the selected applications and their priorities
    $selectedApps = $listBox.SelectedItems

    # Create the batch script
    $batchScript = ":: This is the batch script generated by the Application Launcher script`n`n"
    foreach ($app in $selectedApps) {
        $priority = $prioritySelections[$app]
        $batchScript += "@echo off`n"
        $batchScript += "start /b /$priority /affinity 1 $app`n"
    }

    # Save the batch script to a file
    $saveFileDialog = New-Object System.Windows.Forms.SaveFileDialog
    $saveFileDialog.Filter = "Batch Files (*.bat)|*.bat"
    $saveFileDialog.InitialDirectory = "$env:USERPROFILE\Desktop"
    if ($saveFileDialog.ShowDialog() -eq "OK") {
        $batchFilePath = $saveFileDialog.FileName
        [System.IO.File]::WriteAllText($batchFilePath, $batchScript)
        Write-Host "Batch script saved to $batchFilePath"
    }
})
$form.Controls.Add($generateButton)

# Show the form
$form.Topmost = $true
$result = $form.ShowDialog()
